# SPDX-FileCopyrightText: 2025 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

# This is the yaml file loaded when no config file could be found.

servers:
  dns:
    udp:
      "udp-default":
        address: ":7373"
        readTimeout: 10s
        writeTimeout: 10s
        idleTimeout: 60s
        size: 512
    tcp:
      "tcp-default":
        address: ":7373"
        readTimeout: 10s
        writeTimeout: 10s
        idleTimeout: 60s
        maxQueries: 1024